### DISCUSSION TITLE
Setting user-defined tblproperties

### DISCUSSION THREAD

**Discussion by RealMirage** [dbt-athena/dbt-athena#572] [General]
Is there a supported way through this DBT adapter to add custom tblproperties to our models? I'm working with some Iceberg models I want to tag with custom properties. DBT already tags the models with some of its own custom properties that are exposed in Glue such as "dbt_project_version" or "unique_id" so mostly wondering if there's a way exposed (or something I can make a macro for) that can accomplish this ask.

**Comment by nicor88** [comment]
@RealMirage 
It's not properly documented, but you can use the `meta` field for a table config to push down table properties in glue,
You can add the following into a `schema.yml` for example:

```
  - name: iceberg_example_1
    description: "An example model with iceberg"
    meta:
      contains_pii: true
      custom_prop: this is a custom property
    columns:
      - name: user_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
```
In the example above I added contains_pii and custom_prop, that will be shown as properties in glue catalog.

We can transform this discussion as an issue to document properly this behvior.
