### DISCUSSION TITLE
iceberg incremental model throws Parameter validation failed: Invalid bucket name ""

### DISCUSSION THREAD

**Discussion by Jingye-openc** [dbt-athena/dbt-athena#756] [Q&A] [answered]
Hi 

I have problems with running incremental modelling on iceberg tables with dbt-athena-community. While running full model it is fine, running incremental it throws error like this:
"Parameter validation failed:
Invalid bucket name "": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
"

My project setup 
(~/.dbt/profiles.yml)
```
demo_v2:
  target: v2
  outputs:
    v2:
      type: athena
      s3_staging_dir: s3://my-bucket-athena/dbt/
      s3_data_dir: s3://my-bucket-data-lake/demo_v2/
      s3_tmp_table_dir: s3//my-bucket-data-lake/temp
      s3_data_naming: schema_table
      region_name: eu-west-2
      database:  awsdatacatalog
      schema: demo_v2
      aws_profile_name: playground
      threads: 4
      num_retries: 0
      incremental_strategy: append
      on_schema_change: append_new_columns
```

(dbt_project.yml)
```
name: "demo_v2"
version: "1.0.0"
profile: "demo_v2"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
  - "logs"

require-dbt-version: [">=1.7.0", "<2.0.0"]
seeds:
  demo_v2:  
    +table_type: iceberg
    
models:
    +table_type: iceberg
    +format: parquet
    +incremental_strategy: append
    +on_schema_change: 'append_new_columns'
    +s3_data_naming': 'schema_table'
    +materialized': 'incremental'
    +location': 's3://my-bucket-data-lake/demo_v2/'
    +table_properties:
     {
       'optimize_rewrite_delete_file_threshold': '2',
     }
    demo_v2:
      bronze:
        +enabled: true
```

(config block in a model)
```
{{
    config(
        materialized='incremental'
    )
}}
```

Command I ran:

```
% dbt run -m a_model  -t v2
15:36:13  Running with dbt=1.8.8
15:36:14  Registered adapter: athena=1.8.4
15:36:14  Found 7 models, 6 seeds, 2 sources, 572 macros
15:36:14  
15:36:16  Concurrency: 4 threads (target='v2')
15:36:16  
15:36:16  1 of 1 START sql incremental model demo_v2.a_model ........... [RUN]
15:36:16  Unhandled error while executing 
Parameter validation failed:
Invalid bucket name "": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
15:36:16  1 of 1 ERROR creating sql incremental model demo_v2.a_model .. [ERROR in 0.16s]
15:36:16  
15:36:16  Finished running 1 incremental model in 0 hours 0 minutes and 1.82 seconds (1.82s).
15:36:16  
15:36:16  Completed with 1 error and 0 warnings:
```

Please advice what I did I miss? Thanks

using:
dbt-adapters==1.7.0
dbt-athena-community==1.8.4
dbt-common==1.10.0
dbt-core==1.8.8
dbt-extractor==0.5.1
dbt-semantic-interfaces==0.5.1

**Comment by Jingye-openc** [comment, marked as answer]
I managed to get it working for both full and incremental:
(~/.dbt/profiles.yml)
```
demo_v2:
  target: v2
  outputs:
    v2:
      type: athena
      s3_staging_dir: s3://my-bucket-athena/dbt/
      s3_data_dir: s3://my-bucket-data-lake/demo_v2/
      s3_tmp_table_dir: s3://my-bucket-data-lake/temp
      s3_data_naming: schema_table
      region_name: eu-west-2
      database:  awsdatacatalog
      schema: demo_v2
      aws_profile_name: playground
      threads: 4
      num_retries: 0
```
(dbt_project.yml)
```
name: "demo_v2"
version: "1.0.0"
profile: "demo_v2"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
  - "logs"

require-dbt-version: [">=1.7.0", "<2.0.0"]
seeds:
  demo_v2:  
    +table_type: iceberg
    
models:
    +table_type: iceberg
    +format: parquet
    +incremental_strategy: append
    +on_schema_change: 'append_new_columns'
    +s3_data_naming': 'schema_table'
    +materialized': 'incremental'
    +table_properties:
     {
       'optimize_rewrite_delete_file_threshold': '2',
     }
    demo_v2:
      bronze:
        +enabled: true
```
