### ISSUE TITLE
num_retries doesn't work with env_var

### ISSUE THREAD

**Issue by hagai-arad** [dbt-athena/dbt-athena#110]
Hi, 

I'm using `env_var` in my `profile.yml` file, but when trying to set the `num_retires` attribute with `env_var` it fails with the following error:
```
ERROR: Runtime Error
  Credentials in profile "my_profile", target "dev" invalid: '0' is not valid under any of the given schemas
```

To set the env var I ran this: `export DBT_ATHENA_NUM_RETRIES=0`

My profile.yml:
```
my_profile:
  outputs:
    dev:
      database: "{{ env_var('DBT_ATHENA_DB') }}"
      region_name: "{{ env_var('DBT_REGION_NAME') }}"
      s3_staging_dir: "{{ env_var('DBT_S3_STAGING_DIR') }}"
      schema: "{{ env_var('DBT_ATHENA_SCHEMA') }}"
      type: athena
      num_retries: "{{ env_var('DBT_ATHENA_NUM_RETRIES') }}"
  target: dev
```

A few notes:
- When using the 0 directly it works fine: `num_retries: 0`
- The other attributes are assigned as expected using the `env_var`
