### ISSUE TITLE
s3_data_dir is ignored in some cases

### ISSUE THREAD

**Issue by CommonCrisis** [dbt-athena/dbt-athena#224]
Hi team,

I have no clue what is going on.
My config block is the following:

```
{{ config(
    materialized='table',
    table_type='hive',
    format='orc',
    partition_by=['project_id', 'event_date']
) }}

with...
```

in my dbt_profile.yml this is defined:
```
default:
  target: local
  outputs:
    dev:
      type: athena
      s3_staging_dir: s3://aws-athena-query-results-.../folder_name/
      s3_data_dir: s3://target-bucket-name/dbt_models/
      s3_data_naming: schema_table
      region_name: eu-central-1
      database: awsdatacatalog
      schema: dbt
      work_group: my-workgroup
      threads: 4
    prd:
      type: athena
      s3_staging_dir: s3://aws-athena-query-results-.../folder_name/
      s3_data_dir: s3://target-bucket-name/dbt_models/
      s3_data_naming: schema_table
      region_name: eu-central-1
      database: awsdatacatalog
      schema: dbt
      work_group: my-workgroup
      threads: 4
```

If I build this in target = dev I get this execution in my logs:
```
  create table "schema"."table_name"
  with (
    table_type='hive',
    is_external=true,
    external_location='s3://target-bucket-name/dbt_models/schema/table_name',
    format='orc'
  )
  as
    

with
```
But if I build it with target = prd I get this:

```

On model.schema.table_name: -- /* {"app": "dbt", "dbt_version": "1.4.5", "profile_name": "default", "target_name": "prd", "node_id": "model.schema.table_name"} */

  create table "schema"."table_name"
  with (
    table_type='hive',
    is_external=true,
    format='orc'
  )
  as
    
```

Suddenly the whole `external_location` is missing. I tried to rebuild it multiple times.
The workgroups are defined exactly the same.

I tried to set the `versions_to_keep` to one assuming that somehow somewhere in GLUE the location is saved somehow but I still get the same error.

dev and prd are different AWS environments but both dbt executions are done by the same CI/CD configuration only the target is changed.

I checked the code but I could not find any reason why the `s3_table_prefix` function shouldn't use the defined `s3_data_dir`.

Does anyone have any idea what is going on?
