### ISSUE TITLE
Error running dbt docs generate when sources have database defined

### ISSUE THREAD

**Issue by maiarareinaldo** [dbt-athena/dbt-athena#247]
`dbt docs generate` returns an error when sources are defined with database, for instance:
```yaml
sources:
  - name: source_name
    database: "shared_catalog"
    schema: db_name
```

Error:
`Encountered an error while generating catalog: An error occurred (EntityNotFoundException) when calling the GetTables operation: Database db_name not found.`
