### ISSUE TITLE
Error location property is missing

### ISSUE THREAD

**Issue by tosolveit** [dbt-athena/dbt-athena#257]
Hi,
Using the versions below
dbt-athena-community==1.4.3
dbt-core==1.4.6
Python 3.9.16

I am trying to create an iceberg table as shown in one of the examples of the [documentation](https://github.com/dbt-athena/dbt-athena/blob/main/README.md)
```sql
{{ config(
    materialized='table',
    table_type='iceberg',
    format='parquet',
    partitioned_by=['bucket(user_id, 5)'],
    table_properties={
    	'optimize_rewrite_delete_file_threshold': '2'
    	}
) }}

SELECT
	'A' AS user_id,
	'pi' AS name,
	'active' AS status,
	17.89 AS cost,
	1 AS quantity,
	100000000 AS quantity_big,
	current_date AS my_date
```
I get the following error
```bash
HIVE_DATABASE_LOCATION_ERROR: Schema 'xyz' location cannot be determined. 
Either set the 'location' property when creating the schema, or set the 'hive.metastore.glue.default-warehouse-dir' catalog property.
```

my profiles.yml configuration is
```yaml
personal_schema:
  target: personal
  outputs:
    personal:
      type: athena
      s3_staging_dir: "{{ env_var('DBT_S3_DIR') | as_text }}"
      s3_data_dir: "{{ env_var('DBT_S3_DIR') | as_text }}"
      s3_data_naming: schema_table_unique
      region_name: "{{ env_var('AWS_REGION') | as_text }}"
      schema: "{{ env_var('USER') | as_text }}"
      database: awsdatacatalog
      work_group: "{{ env_var('ATHENA_WORKGROUP') | as_text }}"
      num_retries: 1
      threads: 1
```

When I check the compiled SQL in the logs I see that the location property is missing.
```SQL
 create table "awsdatacatalog"."xyz"."test"
  with (
    table_type='iceberg',
    is_external=false,
    partitioning=ARRAY['bucket(user_id, 5)'],
    format='parquet',
    optimize_rewrite_delete_file_threshold=2
  )
  as
    

SELECT
	'A' AS user_id,
	'pi' AS name,
	'active' AS status,
	17.89 AS cost,
	1 AS quantity,
	100000000 AS quantity_big,
	current_date AS my_date
```
Additional info: Athena query results location is enforced in my case.
