### ISSUE TITLE
Feature: set work_group in dbt_project.yml

### ISSUE THREAD

**Issue by SoumayaMauthoorMOJ** [dbt-athena/dbt-athena#377]
Would it be possible to set `work_group` in `dbt_project.yml`? This means we could assign different queries to different workgroups within a single `dbt run`, for example to separate the curation queries vs the derivation queries. I would be happy to do the work if someone could point me in the right direction. I'm guessing I would need to modify https://github.com/dbt-athena/dbt-athena/blob/main/dbt/adapters/athena/impl.py?

**Comment by nicor88** [comment]
@SoumayaMauthoorMOJ did you try this
```
name: 'my_project'
version: '1.0.0'
config-version: 2


profile: 'my_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  my_project:
    # Config indicated by + and applies to all files under models/example/
    # except if they are explicitly overwritten
    curation:
       work_group: "curation_workgroup"
    derivation:
       work_group: "derivation_workgroup"
```

I didn't test this - therefore I'm not sure that it works - but I expect that it should pick the workgroup per folders in your models.

**Comment by SoumayaMauthoorMOJ** [comment]
Thanks @nicor88 for getting back to me! I should have said that I already tried modifying  `dbt_project.yml` with no luck. I added some additional tags to make sure I was using the right structure:

```
models:
  probation:
    +materialized: table

    curated:
      delius:
        work_group: delius_sandbox # doesn't pick it up
        +meta:
          owner: delius
      oasys:
        work_group: oasys_sandbox # doesn't pick it up
        +meta:
          owner: oasys
```

If I then run `dbt ls --select result:success  --state ./target --output json --output-keys name  meta ` I get:

```
{"name": "delius__store_sales", "meta": {"owner": "delius"}}
{"name": "oasys__call_center", "meta": {"owner": "oasys"}}
{"name": "oasys__catalog_page", "meta": {"owner": "oasys"}}
```
