### ISSUE TITLE
ICEBERG_FILESYSTEM_ERROR

### ISSUE THREAD

**Issue by khoatrandata** [dbt-athena/dbt-athena#437]
Hi everyone, we have also encountered this `ICEBERG_FILESYSTEM_ERROR: Cannot create a table on a non-empty location: s3://...` now with just a dummy query and cleaning the s3 location doesn't help. Logs [here](https://getdbt.slack.com/files/U041Q7UCYBS/F0605QA540M/logs.txt)

```
SELECT 1 as position
{% if is_incremental() %}
    and position > (select coalesce(max(position), 0)
                    from {{ this }})
{% endif %}
```

both in table/incremental mode with

```
config(
        materialized='table',
        table_type='iceberg',
        format='parquet'
    )
or
config(
        materialized='table',
        table_type='iceberg',
        format='parquet',
        on_schema_change='append_new_columns',
        incremental_strategy='append'
    )
```

we are using AWS Administrator access while testing so it's safe to rule out IAM issues.

```
athena_profile:
  target: deploy
  outputs:
    deploy:
      type: "athena"
      work_group: "dbt-land-{{ env_var('DEPLOY', 'dev')|lower }}-s3-lake"
      s3_staging_dir: "s3://dbt-land-{{ env_var('DEPLOY', 'dev')|lower }}-s3-lake-athena-results/dbt/"
      s3_data_dir: "s3://dbt-land-{{ env_var('DEPLOY', 'dev')|lower }}-s3-lake/dbt/"
      s3_data_naming: schema_table_unique
      region_name: "us-west-2"
      database: "awsdatacatalog"
      schema: "dbt-land"
      lf_tags:
        origin: dbt
        team: analytics
      threads: 8
```

after each failure, the s3 location is populated with what seems to be valid data, but I'm guessing somehow this failed subsequently

![image](https://github.com/dbt-athena/dbt-athena/assets/99708686/d0571b12-a161-4f81-ac08-1457bdb72601)
