### ISSUE TITLE
Unable to compile test models in Athena

### ISSUE THREAD

**Issue by borjagonzal** [dbt-athena/dbt-athena#510]
:wave: Hi,

I would like to leverage on this dbt adapter for Athena to transform some data located in S3. 

I have set up a simple dbt project. The profile seems to hold valid values since the connection is successful and a manifest is pushed to the S3 bucket, however I get an issue when parsing the project, which do not provide much information about where the real problems lies:

```
> dbt parse --target data_exports --profiles-dir ./config --single-threaded

  Running with dbt=1.7.1
  Registered adapter: athena=1.7.0
  Unable to do partial parsing because saved manifest not found. Starting full parse.
  Encountered an error:
Runtime Error
  connection never acquired for thread (50595, 8343347328), have []
```

Could you please help me understand why that error is raised and how to make the adapter work in my case :pray:? 

Here is the configuration of my project: 
- dbt_project.yml:
```
name: "data_export"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "default"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  "dbt_date:time_zone": "Europe/Paris"

models:
  data_exports:
    data_exports:
```
- profile.yml:
```
default:
  outputs:
    data_exports:
      type: athena
      s3_staging_dir: "s3://my_bucket/"
      s3_data_dir: "s3://my_bucket/"
      s3_data_naming: schema_table_unique
      region_name: "my_region"
      schema: "my_glue_database"
      database: awsdatacatalog
      work_group: "my_workgroup"

  target: data_exports
```

- model:
```
{{ config(materialized="table", table_type="iceberg") }}


select 'A'          as user_id,
       'pi'         as name,
       'active'     as status,
       17.89        as cost,
       1            as quantity,
       100000000    as quantity_big,
       current_date as my_date
```

The connection setup seems to be working:
```
> dbt debug --target data_exports --profiles-dir ./config

  Running with dbt=1.7.1
  dbt version: 1.7.1
  python version: 3.9.10
  python path: /*****-PLnk2Vdd-py3.9/bin/python
  os info: macOS-13.5-arm64-arm-64bit
  Using profiles dir at ./config
  Using profiles.yml file at ./config/profiles.yml
  Using dbt_project.yml file at /***/dbt_project.yml
  adapter type: athena
  adapter version: 1.7.0
  Configuration:
    profiles.yml file [OK found and valid]
    dbt_project.yml file [OK found and valid]
  Required dependencies:
   - git [OK found]
 
  Connection:
    s3_staging_dir: s3://my_bucket/
    work_group: my_workgroup
    region_name: my_region
    database: awsdatacatalog
    schema: my_glue_database
    poll_interval: 1.0
    aws_profile_name: None
    aws_access_key_id: None
    aws_secret_access_key: None
    aws_session_token: None
    endpoint_url: None
    s3_data_dir: s3://my_bucket/
    s3_data_naming: schema_table_unique
    s3_tmp_table_dir: None
    debug_query_state: False
    seed_s3_upload_args: None
    lf_tags_database: None
  Registered adapter: athena=1.7.0
    Connection test: [OK connection ok]

  All checks passed!
```
