### ISSUE TITLE
[Feature] Table name prefix via profile configuration

### ISSUE THREAD

**Issue by dacreify** [dbt-athena/dbt-athena#581]
### Is this your first time submitting a feature request?

- [X] I have searched the existing issues, and I could not find an existing issue for this feature

### Describe the feature

Our use case is many developers all working on and running models within the same database. In order for there not to be table name collisions we need a way to put each developer in their own table namespace within that single database.

With other drivers, like `dbt-postgres`, it's possible to use the `schema:` profile configuration along with an environment variable to do this automatically. For example:

```
my_postgres_dwh:
  target: my-target
  outputs:
    my-target:
      schema: "dbt_{{ env_var('USER') }}"
      ...
 ```

This will cause all tables to be in schemas named for the user running the command. For example: `dbt_myuser_schema_name.model_name`

For this feature maybe we could have:

```
my_athena_dl:
  target: my-target
  outputs:
    my-target:
      table_name_prefix: "dbt_{{ env_var('USER') }}_"
      ...
 ```

This will cause all tables to be prefixed with the name of the user running the command. For example: `dbt_myuser_model_name`

### Describe alternatives you've considered

We considered provisioning a separate database per user but this would involve friction and overhead.

### Who will this benefit?

Useful for anybody that wants to have multi user Glue databases for developing DBT projects!

### Are you interested in contributing this feature?

Yes

**Comment by nicor88** [comment]
I don't think that you need a specific adapter implementation for this.

I achieve what you suggested simply with the following approach:
* overwridde the get_schema_macro
```
{% macro generate_schema_name(custom_schema_name, node) -%}
  {%- set default_schema = target.schema -%}

  {%- if 'development' in target.name or 'ci' in target.name -%}
    {{ default_schema | trim }}
  {%- else -%}
    {%- if custom_schema_name is none -%}
      {{ default_schema | trim}}
    {%- else -%}
      {{ custom_schema_name | trim }}
    {%- endif -%}
  {%- endif -%}

{%- endmacro %}
```
* use a specific profile for development e.g. `development` e.g.
```
config:
  send_anonymous_usage_stats: false

zolar:
  outputs:
    development:
      aws_profile_name: your-aws-profile
      database: awsdatacatalog
      region_name: eu-central-1
      s3_staging_dir: "...."
      s3_data_dir: "...."
      s3_data_naming: table_unique
      schema: "{{ env_var('DBT_DEFAULT_DB')}}"
      type: athena
      threads: 3
      num_retries: 0
      work_group: "dbt-development"
  target: "development_staging"
```

The above config requires an .env file with a variable DBT_DEFAULT_DB that must be sourced by every developer to allow to use the proper dbt database.

Doing the above the people working with dbt have their own database, therefore name collision won't never happen.
At the same time ref still works, and tables are created and referenced from the developer database.
