### ISSUE TITLE
[Feature] Assign LFTags to source tables

### ISSUE THREAD

**Issue by rstml** [dbt-athena/dbt-athena#706]
### Is this your first time submitting a feature request?

- [X] I have searched the existing issues, and I could not find an existing issue for this feature

### Describe the feature

I'd like to manage all LF-Tags associations centrally, inside of the dbt project, including LF-Tags for the source tables. See [for the context](https://github.com/dbt-athena/dbt-athena/discussions/603).

### Describe alternatives you've considered

I tried to to add tags to dbt_project.yml as described [here](https://github.com/dbt-athena/dbt-athena?tab=readme-ov-file#table-configuration) but it had no impact:

```
models:
  bronze:
    demo_transactions:
      +lf_tags_config:
        enabled: true
        tags:
          'Group:Team1': 'true'
```

### Who will this benefit?

Anyone who has source tables defined in dbt. This would help centralise LFTags management across all tables.

### Are you interested in contributing this feature?

Yes. I'm new to dbt and dbt adaptors. A few pointers would help to get started with.

### Anything else?

I'm already using [dbt-athena-external-tables](https://github.com/dbt-athena/dbt-athena-external-tables). Is it better idea to implement this functionality in this module?
